### ISSUE TITLE
Bindgen inconsistency between Windows and Linux

### ISSUE THREAD

**Issue by Fernthedev** [bbqsrc/cargo-ndk#156]
Using `--bindgen` on Linux (through WSL) I am able to generate bindings from my C library correctly in my `build.rs` file, as recommended by the official Rust Bindgen Docs. However, on Windows it cannot find `stdbool.h` etc. headers. 

I noticed that running both WSL and Windows with `-vv` flag, I get various information indicating that the sysroot, include header directories and targets are correct. But I noticed certain oddities between Windows and Linux. Specifically, Linux adds the system host's include headers, e.g ` /usr/include/clang/19.1.6/include` while Windows does not. I suspect either Windows is not properly configuring the header includes or Linux might be leaking the wrong headers and using those instead of the NDK toolchain's headers. I'm not sure which is the correct solution in this case. 

NDK does contain the `stdbool.h` headers, but at `${sysroot}/usr/include/c++/v1`. I found no indication of this header being added in CMake's toolchain setup, so I have to assume clang would somehow find these somehow. I apologize if this is just a missing flag issue.

I downloaded LLVM through `winget` and `apt` respectively.

Output:
Windows
```shell
❯ cargo ndk --bindgen -t arm64-v8a -- -vv clippy
    Detected NDK v27.2.12479018 (E:\SSDUse\AppData\Android\SDK\ndk\27.2.12479018+preview-0) [ANDROID_NDK_HOME]
   Exporting CARGO_NDK_CMAKE_TOOLCHAIN_PATH="E:\\SSDUse\\AppData\\Android\\SDK\\ndk\\27.2.12479018+preview-0\\build\\cmake\\android.toolchain.cmake"
     Setting Android SDK platform level to 21
    Building targets (arm64-v8a)
    Building arm64-v8a (aarch64-linux-android)
   Exporting CARGO_NDK_ANDROID_TARGET="arm64-v8a"
   Exporting AR_aarch64-linux-android="E:\\SSDUse\\AppData\\Android\\SDK\\ndk\\27.2.12479018+preview-0\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\llvm-ar"
   Exporting BINDGEN_EXTRA_CLANG_ARGS_aarch64_linux_android="--sysroot=E:/SSDUse/AppData/Android/SDK/ndk/27.2.12479018+preview-0/toolchains/llvm/prebuilt/windows-x86_64/sysroot -IE:/SSDUse/AppData/Android/SDK/ndk/27.2.12479018+preview-0/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/aarch64-linux-android"
   Exporting CARGO_NDK_SYSROOT_LIBS_PATH="E:\\SSDUse\\AppData\\Android\\SDK\\ndk\\27.2.12479018+preview-0\\toolchains\\llvm\\prebuilt\\windows-x86_64\\sysroot\\usr\\lib\\aarch64-linux-android"
   Exporting CARGO_NDK_SYSROOT_PATH="E:\\SSDUse\\AppData\\Android\\SDK\\ndk\\27.2.12479018+preview-0\\toolchains\\llvm\\prebuilt\\windows-x86_64\\sysroot"
   Exporting CARGO_NDK_SYSROOT_TARGET="aarch64-linux-android"
   Exporting CARGO_TARGET_AARCH64_LINUX_ANDROID_AR="E:\\SSDUse\\AppData\\Android\\SDK\\ndk\\27.2.12479018+preview-0\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\llvm-ar"
   Exporting CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER="\\\\?\\C:\\Users\\fernr\\.cargo\\bin\\cargo-ndk"
   Exporting CC_aarch64-linux-android="E:\\SSDUse\\AppData\\Android\\SDK\\ndk\\27.2.12479018+preview-0\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\clang"
   Exporting CFLAGS_aarch64-linux-android="--target=aarch64-linux-android21"
   Exporting CXXFLAGS_aarch64-linux-android="--target=aarch64-linux-android21"
   Exporting CXX_aarch64-linux-android="E:\\SSDUse\\AppData\\Android\\SDK\\ndk\\27.2.12479018+preview-0\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\clang++"
   Exporting RANLIB_aarch64-linux-android="E:\\SSDUse\\AppData\\Android\\SDK\\ndk\\27.2.12479018+preview-0\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\llvm-ranlib"
   Exporting _CARGO_NDK_LINK_CLANG="E:\\SSDUse\\AppData\\Android\\SDK\\ndk\\27.2.12479018+preview-0\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\clang"
   Exporting _CARGO_NDK_LINK_TARGET="--target=aarch64-linux-android21"
    Invoking cargo (\\?\C:\Users\fernr\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\bin\cargo.exe) with args: ["-vv", "clippy"]
   Compiling scotland2_rs v0.1.0 (E:\SSDUse\ProgrammingProjects\CLionProjects\scotland2_rs)
error: failed to run custom build command for `scotland2_rs v0.1.0 (E:\SSDUse\ProgrammingProjects\CLionProjects\scotland2_rs)`

Caused by:
  process didn't exit successfully: `E:\SSDUse\ProgrammingProjects\CLionProjects\scotland2_rs\target\debug\build\scotland2_rs-4a4b85f3b197a663\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=wrapper.h
  cargo:rerun-if-changed=qpm.json
  Took 513ms to dependency resolve
  Pulling scotland2:0.1.6
  Warning, adding to cache permanently to multiple repos!
  Saved local repository Config!
  Copying now
  cargo:rerun-if-changed=E:\SSDUse\ProgrammingProjects\CLionProjects\scotland2_rs\target\aarch64-linux-android\debug\build\scotland2_rs-060bd71eb06fcc89\out\qpm.shared.json
  cargo:rerun-if-env-changed=TARGET
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_aarch64-linux-android
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_aarch64_linux_android

  --- stderr
  Downloading sl2 from qpm
  Generating bindings for scotland2
  E:\SSDUse\ProgrammingProjects\CLionProjects\scotland2_rs\wrapper.h:2:26: fatal error: 'stdbool.h' file not found
  thread 'main' panicked at build.rs:70:10:
  Unable to generate bindings: ClangDiagnostic("E:\\SSDUse\\ProgrammingProjects\\CLionProjects\\scotland2_rs\\wrapper.h:2:26: fatal error: 'stdbool.h' file not found\n")
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
note: If the build failed due to a missing target, you can run this command:
note:
note:     rustup target install aarch64-linux-android
```

WSL Ubuntu 22.04 (force induced panic to show log)
```
> cargo ndk --bindgen -t arm64-v8a -p 28 -- -vv clippy
    Detected NDK v27.2.12479018 (/home/fern/android/ndk/27.2.12479018+preview-0) [ANDROID_NDK_HOME]
   Exporting CARGO_NDK_CMAKE_TOOLCHAIN_PATH="/home/fern/android/ndk/27.2.12479018+preview-0/build/cmake/android.toolchain.cmake"
     Setting Android SDK platform level to 28
    Building targets (arm64-v8a)
    Building arm64-v8a (aarch64-linux-android)
   Exporting CARGO_NDK_ANDROID_PLATFORM="arm64-v8a"
   Exporting ANDROID_PLATFORM=28
   Exporting ANDROID_ABI="arm64-v8a"
   Exporting AR_aarch64-linux-android="/home/fern/android/ndk/27.2.12479018+preview-0/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"
   Exporting BINDGEN_EXTRA_CLANG_ARGS_aarch64_linux_android="--sysroot=/home/fern/android/ndk/27.2.12479018+preview-0/toolchains/llvm/prebuilt/linux-x86_64/sysroot -I/home/fern/android/ndk/27.2.12479018+preview-0/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/aarch64-linux-android"
   Exporting CARGO_NDK_SYSROOT_LIBS_PATH="/home/fern/android/ndk/27.2.12479018+preview-0/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android"
   Exporting CARGO_NDK_SYSROOT_PATH="/home/fern/android/ndk/27.2.12479018+preview-0/toolchains/llvm/prebuilt/linux-x86_64/sysroot"
   Exporting CARGO_NDK_SYSROOT_TARGET="aarch64-linux-android"
   Exporting CARGO_TARGET_AARCH64_LINUX_ANDROID_AR="/home/fern/android/ndk/27.2.12479018+preview-0/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"
   Exporting CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER="/home/fern/.cargo/bin/cargo-ndk"
   Exporting CC_aarch64-linux-android="/home/fern/android/ndk/27.2.12479018+preview-0/toolchains/llvm/prebuilt/linux-x86_64/bin/clang"
   Exporting CFLAGS_aarch64-linux-android="--target=aarch64-linux-android28"
   Exporting CXXFLAGS_aarch64-linux-android="--target=aarch64-linux-android28"
   Exporting CXX_aarch64-linux-android="/home/fern/android/ndk/27.2.12479018+preview-0/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++"
   Exporting RANLIB_aarch64-linux-android="/home/fern/android/ndk/27.2.12479018+preview-0/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib"
   Exporting _CARGO_NDK_LINK_CLANG="/home/fern/android/ndk/27.2.12479018+preview-0/toolchains/llvm/prebuilt/linux-x86_64/bin/clang"
   Exporting _CARGO_NDK_LINK_TARGET="--target=aarch64-linux-android28"
    Invoking cargo (/home/fern/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo) with args: ["-vv", "clippy"]

Caused by:
  process didn't exit successfully: `/home/fern/projects/scotland2_rs/target/debug/build/scotland2_rs-8a9d8d91c5629c87/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=wrapper.h
  cargo:rerun-if-changed=qpm.json
  Took 406ms to dependency resolve
  Pulling scotland2:0.1.6
  Warning, adding to cache permanently to multiple repos!
  Saved local repository Config!
  Copying now
  cargo:rerun-if-changed=/home/fern/projects/scotland2_rs/target/aarch64-linux-android/debug/build/scotland2_rs-13294fb59a618273/out/qpm.shared.json
  cargo:rerun-if-env-changed=TARGET
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_aarch64-linux-android
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_aarch64_linux_android
  cargo:rerun-if-changed=/usr/lib/llvm-19/lib/clang/19/include/stdbool.h
  cargo:rerun-if-changed=/home/fern/projects/scotland2_rs/target/aarch64-linux-android/debug/build/scotland2_rs-13294fb59a618273/out/extern/includes/scotland2/shared/modloader.h
  cargo:rerun-if-changed=/home/fern/android/ndk/android-ndk-r27-canary/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/jni.h
  cargo:rerun-if-changed=/usr/lib/llvm-19/lib/clang/19/include/stdarg.h
  cargo:rerun-if-changed=/usr/lib/llvm-19/lib/clang/19/include/__stdarg_header_macro.h
  cargo:rerun-if-changed=/usr/lib/llvm-19/lib/clang/19/include/__stdarg___gnuc_va_list.h
  cargo:rerun-if-changed=/usr/lib/llvm-19/lib/clang/19/include/__stdarg_va_list.h
  cargo:rerun-if-changed=/usr/lib/llvm-19/lib/clang/19/include/__stdarg_va_arg.h
  cargo:rerun-if-changed=/usr/lib/llvm-19/lib/clang/19/include/__stdarg___va_copy.h
  cargo:rerun-if-changed=/usr/lib/llvm-19/lib/clang/19/include/__stdarg_va_copy.h
  cargo:rerun-if-changed=/usr/lib/llvm-19/lib/clang/19/include/stdint.h
  cargo:rerun-if-changed=/home/fern/android/ndk/android-ndk-r27-canary/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/stdint.h
  cargo:rerun-if-changed=/home/fern/android/ndk/android-ndk-r27-canary/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/bits/wchar_limits.h
  cargo:rerun-if-changed=/home/fern/android/ndk/android-ndk-r27-canary/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/sys/cdefs.h
  cargo:rerun-if-changed=/home/fern/android/ndk/android-ndk-r27-canary/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/android/versioning.h
  cargo:rerun-if-changed=/home/fern/android/ndk/android-ndk-r27-canary/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/android/api-level.h
  cargo:rerun-if-changed=/home/fern/android/ndk/android-ndk-r27-canary/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/sys/cdefs.h
  cargo:rerun-if-changed=/home/fern/android/ndk/android-ndk-r27-canary/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/android/ndk-version.h
  cargo:rerun-if-changed=/usr/lib/llvm-19/lib/clang/19/include/stddef.h
  cargo:rerun-if-changed=/usr/lib/llvm-19/lib/clang/19/include/__stddef_header_macro.h
  cargo:rerun-if-changed=/usr/lib/llvm-19/lib/clang/19/include/__stddef_ptrdiff_t.h
  cargo:rerun-if-changed=/usr/lib/llvm-19/lib/clang/19/include/__stddef_size_t.h
  cargo:rerun-if-changed=/usr/lib/llvm-19/lib/clang/19/include/__stddef_wchar_t.h
  cargo:rerun-if-changed=/usr/lib/llvm-19/lib/clang/19/include/__stddef_null.h
  cargo:rerun-if-changed=/usr/lib/llvm-19/lib/clang/19/include/__stddef_max_align_t.h
  cargo:rerun-if-changed=/usr/lib/llvm-19/lib/clang/19/include/__stddef_offsetof.h
  cargo:rerun-if-changed=/home/fern/android/ndk/android-ndk-r27-canary/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/sys/cdefs.h
  cargo:rerun-if-changed=/usr/lib/llvm-19/lib/clang/19/include/stdint.h
  cargo:rerun-if-changed=/home/fern/projects/scotland2_rs/target/aarch64-linux-android/debug/build/scotland2_rs-13294fb59a618273/out/extern/includes/scotland2/shared/_config.h
  cargo:rustc-link-search=/home/fern/projects/scotland2_rs/target/aarch64-linux-android/debug/build/scotland2_rs-13294fb59a618273/out/extern/libs
  cargo:rustc-link-lib=sl2

  --- stderr
  Downloading sl2 from qpm
  Generating bindings for scotland2
  Ubuntu clang version 19.1.6 (++20241217105927+657e03f8625c-1~exp1~20241217105943.71)
  Target: aarch64-unknown-linux-android
  Thread model: posix
  InstalledDir: 
  ignoring nonexistent directory "/home/fern/android/ndk/android-ndk-r27-canary/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/local/include"
  ignoring nonexistent directory "/home/fern/android/ndk/android-ndk-r27-canary/toolchains/llvm/prebuilt/linux-x86_64/sysroot/include"
  ignoring duplicate directory "/home/fern/android/ndk/android-ndk-r27-canary/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/aarch64-linux-android"
    as it is a non-system directory that duplicates a system directory
  ignoring duplicate directory "/usr/include/clang/19.1.6/include"
  ignoring duplicate directory "/home/fern/android/ndk/android-ndk-r27-canary/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/aarch64-linux-android"
  ignoring duplicate directory "/home/fern/android/ndk/android-ndk-r27-canary/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include"
  #include "..." search starts here:
  #include <...> search starts here:
   /usr/lib/llvm-19/lib/clang/19/include
   /home/fern/android/ndk/android-ndk-r27-canary/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/aarch64-linux-android
   /home/fern/android/ndk/android-ndk-r27-canary/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include
  End of search list.
  thread 'main' panicked at build.rs:108:5:
  explicit panic
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
note: If the build failed due to a missing target, you can run this command:
note: 
note:     rustup target install aarch64-linux-android
```

Repo where issue can be observed. I can make a smaller reproduction if required <https://github.com/QuestPackageManager/scotland2_rs/>

To be clear, I'm not sure who this issue should be directed at. I hope here I'll have some help figuring this out, since ideally I'd like to avoid having to resort to manually generating these bindings through the CLI myself. If more information or clarity is required, I'll be open to share more. Thank you.

**Comment by bbqsrc** [comment]
Have you tried with the unpublished main branch? Let me know if that behavior is the same.

**Comment by Fernthedev** [comment]
Hi, nothing seems to have changed with the latest commits. https://github.com/bbqsrc/cargo-ndk/compare/a81d7ed294410434c7d571b4ccf063ac0ae36a4f...main

Might I ask if you're referring to other changes that do not seem to be committed a this point in time? I see nothing related to my issue in the changes.  

Thanks for taking a quick look!
